# Generated by Django 5.1.1 on 2025-01-10 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Format nomor telepon harus dimulai dengan 08 dan diikuti 8-13 digit angka', regex='^08[0-9]{8,13}$')])),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False, 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='suppliers',
        ),
    ]
