# Generated by Django 5.1.1 on 2025-01-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_sale_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
